#!/usr/bin/env bash
# Assembles work/bundle: GemRB + its libraries + a private glibc + an embedded Python, laid out for /media/fat/gemrb.
#   gemrb, plugins/, GUIScripts/, unhardcoded/, override/   the engine
#   libs/     SDL2 (with the MiSTer drivers), SDL2_mixer, Python, zlib, libpng, FreeType, Vorbis, glibc, libstdc++, gconv/
#   python/   the trimmed Python standard library
#   game/     your Baldur's Gate 2 files (added by deploy.sh data)
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/env.sh"

INSTALL="$WORK/gemrb-install/media/fat/gemrb"
OUT="$WORK/bundle/gemrb"
DEVICE_DIR="${DEVICE_DIR:-/media/fat/gemrb}"
STRIP=arm-linux-gnueabihf-strip
PYV="${PYTHON_VER%.*}"
CXX_LIB=$(dirname "$(arm-linux-gnueabihf-g++ -print-file-name=libstdc++.so.6)")

rm -rf "$WORK/bundle"; mkdir -p "$OUT/libs" "$OUT/python/lib"
mkdir -p "$WORK/bundle/Scripts"

# The engine.
cp -a "$INSTALL/gemrb" "$INSTALL"/libgemrb_core.so* "$INSTALL/plugins" "$INSTALL/GUIScripts" \
	"$INSTALL/unhardcoded" "$INSTALL/override" "$OUT/"

# Libraries: the ones built here, then a private glibc so the MiSTer's old one is not used.
for l in libSDL2-2.0.so.0 libSDL2_mixer-2.0.so.0 libpython$PYV.so.1.0 libz.so.1 libpng16.so.16 \
         libfreetype.so.6 libogg.so.0 libvorbis.so.0.4.9 libvorbisfile.so.3.3.8; do
	cp -L "$PREFIX/lib/$l" "$OUT/libs/"
done
for l in ld-linux-armhf.so.3 libc.so.6 libm.so.6; do cp -L "$SYSROOT/lib/$l" "$OUT/libs/"; done
cp -L "$CXX_LIB/libstdc++.so.6" "$CXX_LIB/libgcc_s.so.1" "$OUT/libs/"
# Text conversion (iconv) loads charset modules from disk; take them from the matching armhf libc6 package.
GLIBC_DEB="libc6_${GLIBC_DEB_VER:-2.43-2ubuntu2}_armhf.deb"
[ -s "$DL/$GLIBC_DEB" ] || curl -fsSL -o "$DL/$GLIBC_DEB" "http://ports.ubuntu.com/ubuntu-ports/pool/main/g/glibc/$GLIBC_DEB"
rm -rf "$WORK/libc6-x"; mkdir -p "$WORK/libc6-x"; dpkg-deb -x "$DL/$GLIBC_DEB" "$WORK/libc6-x"
cp -r "$WORK"/libc6-x/usr/lib/arm-linux-gnueabihf/gconv "$OUT/libs/gconv"

$STRIP --strip-unneeded "$OUT/gemrb" "$OUT"/libgemrb_core.so* "$OUT"/plugins/*.so "$OUT"/libs/*.so* 2>/dev/null || true
patchelf --set-interpreter "$DEVICE_DIR/libs/ld-linux-armhf.so.3" --set-rpath '$ORIGIN:$ORIGIN/libs' "$OUT/gemrb"
patchelf --set-rpath '$ORIGIN/libs' "$OUT"/libgemrb_core.so*
for p in "$OUT"/plugins/*.so; do patchelf --set-rpath '$ORIGIN/..:$ORIGIN/../libs' "$p"; done
for l in "$OUT"/libs/*.so*; do case "$l" in */ld-linux*) ;; *) patchelf --set-rpath '$ORIGIN' "$l" ;; esac; done

# The Python standard library, trimmed to what an embedded interpreter needs, with bytecode that does not
# depend on file timestamps (which unpacking a zip can change).
PYL="$OUT/python/lib/python$PYV"
mkdir -p "$PYL"
tar -C "$PREFIX/lib/python$PYV" -cf - \
	--exclude='test' --exclude='tests' --exclude='idlelib' --exclude='tkinter' --exclude='turtledemo' \
	--exclude='ensurepip' --exclude='lib2to3' --exclude='site-packages' --exclude='config-*' \
	--exclude='turtle.py' --exclude='__pycache__' . | tar -C "$PYL" -xf -
$STRIP --strip-unneeded "$PYL"/lib-dynload/*.so 2>/dev/null || true
for l in "$PYL"/lib-dynload/*.so; do patchelf --set-rpath '$ORIGIN/../../../../libs' "$l" 2>/dev/null || true; done
"$HOSTPREFIX/bin/python$PYV" -m compileall -q -j0 --invalidation-mode unchecked-hash "$PYL" "$OUT/GUIScripts" >/dev/null

cat > "$OUT/GemRB.cfg" <<CFG
# Generated by scripts/bundle.sh. Edit /media/fat/gemrb/GemRB.cfg to change GemRB's settings.
GameType=bg2
GamePath=$DEVICE_DIR/game
GemRBPath=$DEVICE_DIR
GUIScriptsPath=$DEVICE_DIR
GemRBUnhardcodedPath=$DEVICE_DIR
PluginsPath=$DEVICE_DIR/plugins
CachePath=$DEVICE_DIR/cache
SavePath=$DEVICE_DIR/save
Width=800
Height=600
Bpp=32
AudioDriver=sdlaudio
CapFPS=30
Logging=1
# The intro videos play choppily on the MiSTer (and 0 plays them).
SkipIntroVideos=1
# Fog of war drawn with sprites (as in the original game) instead of blended triangles, which SDL draws slowly in software.
SpriteFogOfWar=1
CFG

cat > "$OUT/run.sh" <<'RUN'
#!/bin/sh
# Starts GemRB on the MiSTer.  Extra arguments go to gemrb.
# Optional settings go in /media/fat/gemrb/env.sh:
#   MISTER_OUTPUT_MODE=800x600|off   HDMI output mode while playing (default 800x600)
#   MISTER_RESTORE_MODE="<modeline>" mode to switch back to afterwards (default 1080p60)
#   MISTER_SWAP_MB=384               size of the emergency swap file on the SD card (0 = none)
D=/media/fat/gemrb
cd "$D" || exit 1
[ -f "$D/GemRB.cfg" ] || { [ -f "$D/GemRB.cfg.default" ] && cp "$D/GemRB.cfg.default" "$D/GemRB.cfg"; }
[ -f "$D/env.sh" ] && . "$D/env.sh"
mkdir -p "$D/cache" "$D/save"
export GCONV_PATH="$D/libs/gconv" PYTHONHOME="$D/python" PYTHONDONTWRITEBYTECODE=1
export SDL_VIDEODRIVER="${SDL_VIDEODRIVER:-mister}" SDL_AUDIODRIVER="${SDL_AUDIODRIVER:-mister}"
export SDL_RENDER_DRIVER="${SDL_RENDER_DRIVER:-software}"
# An alpha-less window surface lets SDL use its fast NEON blitter for the final composite.
export SDL_MISTER_FORMAT="${SDL_MISTER_FORMAT:-xrgb}"

# The MiSTer has about 490 MB of RAM and no swap, and a big fight (creature animations) plus a save can need more
# than that: the kernel then kills the game. So keep an emergency swap file on the SD card. The kernel is told to use it
# only as a last resort (swappiness 5), so normal play does not touch the card. It is created in the background the
# first time, and switched off again when the game exits.
SWAPFILE="$D/swapfile"
swap_off() {
    for dev in $(losetup -a 2>/dev/null | grep "$SWAPFILE" | cut -d: -f1); do
        swapoff "$dev" 2>/dev/null
        losetup -d "$dev" 2>/dev/null
    done
    [ -n "$old_swappiness" ] && echo "$old_swappiness" > /proc/sys/vm/swappiness
}
swap_on() {
    [ "${MISTER_SWAP_MB:-384}" -gt 0 ] 2>/dev/null || return 0
    size=$(( ${MISTER_SWAP_MB:-384} * 1048576 ))
    if [ ! -f "$SWAPFILE" ] || [ "$(stat -c %s "$SWAPFILE")" != "$size" ]; then
        rm -f "$SWAPFILE"
        dd if=/dev/zero of="$SWAPFILE" bs=1M count="${MISTER_SWAP_MB:-384}" 2>/dev/null || { rm -f "$SWAPFILE"; return 1; }
    fi
    dev=$(losetup -f) || return 1
    losetup "$dev" "$SWAPFILE" && mkswap "$dev" >/dev/null 2>&1 && swapon -p 0 "$dev" 2>/dev/null || { losetup -d "$dev" 2>/dev/null; return 1; }
    echo 5 > /proc/sys/vm/swappiness
}
old_swappiness=$(cat /proc/sys/vm/swappiness 2>/dev/null)
swap_off                                # clean up after a run that did not exit normally
swap_on &

# The scaler only scales the framebuffer by whole numbers, so switch the HDMI output itself to the
# game's resolution (the display scales it to fill the screen) and restore it afterwards.
MODE_800X600="800,40,128,88,600,1,4,23,40000,+hsync,+vsync"        # VESA 800x600 @ 60 Hz
MODE_1080P60="1920,88,44,148,1080,4,5,36,148500,+hsync,+vsync"     # CEA 1080p @ 60 Hz
switched=0
if [ "${MISTER_OUTPUT_MODE:-800x600}" = 800x600 ] && [ -p /dev/MiSTer_cmd ]; then
    echo "video_mode $MODE_800X600" > /dev/MiSTer_cmd
    switched=1
    sleep 2.5   # let the display re-sync; Main resizes the framebuffer to match
fi
"$D/gemrb" -c "$D/GemRB.cfg" "$@" &
child=$!
trap 'kill -TERM $child 2>/dev/null' TERM HUP INT
wait $child
rc=$?
wait $child 2>/dev/null
swap_off
if [ "$switched" = 1 ]; then
    echo "video_mode ${MISTER_RESTORE_MODE:-$MODE_1080P60}" > /dev/MiSTer_cmd
    sleep 1
fi
exit $rc
RUN
chmod +x "$OUT/run.sh"

# Entry for the OSD Scripts menu (F12 > Scripts).
printf '#!/bin/bash\nexec %s/run.sh "$@"\n' "$DEVICE_DIR" > "$WORK/bundle/Scripts/gemrb.sh"
chmod +x "$WORK/bundle/Scripts/gemrb.sh"
du -sh "$WORK/bundle"; du -sh "$OUT"/*
