#!/usr/bin/env bash
# Assembles work/bundle: GemRB + its libraries + a private glibc + an embedded Python, laid out for /media/fat/gemrb.
#   gemrb, plugins/, GUIScripts/, unhardcoded/, override/   the engine
#   libs/     SDL2 (with the MiSTer drivers), SDL2_mixer, Python, zlib, libpng, FreeType, Vorbis, glibc, libstdc++, gconv/
#   python/   the trimmed Python standard library
#   game/     your Baldur's Gate 2 files (added by deploy.sh data)
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/env.sh"

INSTALL="$WORK/gemrb-install/media/fat/gemrb"
OUT="$WORK/bundle/gemrb"
DEVICE_DIR="${DEVICE_DIR:-/media/fat/gemrb}"
STRIP=arm-linux-gnueabihf-strip
PYV="${PYTHON_VER%.*}"
CXX_LIB=$(dirname "$(arm-linux-gnueabihf-g++ -print-file-name=libstdc++.so.6)")

rm -rf "$WORK/bundle"; mkdir -p "$OUT/libs" "$OUT/python/lib"
mkdir -p "$WORK/bundle/Scripts"

# The engine.
cp -a "$INSTALL/gemrb" "$INSTALL"/libgemrb_core.so* "$INSTALL/plugins" "$INSTALL/GUIScripts" \
	"$INSTALL/unhardcoded" "$INSTALL/override" "$OUT/"

# Libraries: the ones built here, then a private glibc so the MiSTer's old one is not used.
for l in libSDL2-2.0.so.0 libSDL2_mixer-2.0.so.0 libpython$PYV.so.1.0 libz.so.1 libpng16.so.16 \
         libfreetype.so.6 libogg.so.0 libvorbis.so.0.4.9 libvorbisfile.so.3.3.8; do
	cp -L "$PREFIX/lib/$l" "$OUT/libs/"
done
for l in ld-linux-armhf.so.3 libc.so.6 libm.so.6; do cp -L "$SYSROOT/lib/$l" "$OUT/libs/"; done
cp -L "$CXX_LIB/libstdc++.so.6" "$CXX_LIB/libgcc_s.so.1" "$OUT/libs/"
# Text conversion (iconv) loads charset modules from disk; take them from the matching armhf libc6 package.
GLIBC_DEB="libc6_${GLIBC_DEB_VER:-2.43-2ubuntu2}_armhf.deb"
[ -s "$DL/$GLIBC_DEB" ] || curl -fsSL -o "$DL/$GLIBC_DEB" "http://ports.ubuntu.com/ubuntu-ports/pool/main/g/glibc/$GLIBC_DEB"
rm -rf "$WORK/libc6-x"; mkdir -p "$WORK/libc6-x"; dpkg-deb -x "$DL/$GLIBC_DEB" "$WORK/libc6-x"
cp -r "$WORK"/libc6-x/usr/lib/arm-linux-gnueabihf/gconv "$OUT/libs/gconv"
cp -L "$WORK"/libc6-x/usr/lib/arm-linux-gnueabihf/libc_malloc_debug.so.0 "$OUT/libs/"   # only used by MISTER_MALLOC_CHECK=1

$STRIP --strip-unneeded "$OUT/gemrb" "$OUT"/libgemrb_core.so* "$OUT"/plugins/*.so "$OUT"/libs/*.so* 2>/dev/null || true
patchelf --set-interpreter "$DEVICE_DIR/libs/ld-linux-armhf.so.3" --set-rpath '$ORIGIN:$ORIGIN/libs' "$OUT/gemrb"
patchelf --set-rpath '$ORIGIN/libs' "$OUT"/libgemrb_core.so*
for p in "$OUT"/plugins/*.so; do patchelf --set-rpath '$ORIGIN/..:$ORIGIN/../libs' "$p"; done
for l in "$OUT"/libs/*.so*; do case "$l" in */ld-linux*) ;; *) patchelf --set-rpath '$ORIGIN' "$l" ;; esac; done

# The Python standard library, trimmed to what an embedded interpreter needs, with bytecode that does not
# depend on file timestamps (which unpacking a zip can change).
PYL="$OUT/python/lib/python$PYV"
mkdir -p "$PYL"
tar -C "$PREFIX/lib/python$PYV" -cf - \
	--exclude='test' --exclude='tests' --exclude='idlelib' --exclude='tkinter' --exclude='turtledemo' \
	--exclude='ensurepip' --exclude='lib2to3' --exclude='site-packages' --exclude='config-*' \
	--exclude='turtle.py' --exclude='__pycache__' . | tar -C "$PYL" -xf -
$STRIP --strip-unneeded "$PYL"/lib-dynload/*.so 2>/dev/null || true
for l in "$PYL"/lib-dynload/*.so; do patchelf --set-rpath '$ORIGIN/../../../../libs' "$l" 2>/dev/null || true; done
"$HOSTPREFIX/bin/python$PYV" -m compileall -q -j0 --invalidation-mode unchecked-hash "$PYL" "$OUT/GUIScripts" >/dev/null

# One default config per game (the launcher copies it to GemRB-<game>.cfg on the first run, and never overwrites that).
# Baldur's Gate 1 only supports 640x480 (GemRB's docs), the later games 800x600 and up.
write_cfg() {  # write_cfg <game> <GameType> <width> <height>
	cat > "$OUT/GemRB-$1.cfg.default" <<CFG
# Generated by scripts/bundle.sh. Edit /media/fat/gemrb/GemRB-$1.cfg to change GemRB's settings for this game.
GameType=$2
GamePath=$DEVICE_DIR/games/$1
GemRBPath=$DEVICE_DIR
GUIScriptsPath=$DEVICE_DIR
GemRBUnhardcodedPath=$DEVICE_DIR
PluginsPath=$DEVICE_DIR/plugins
CachePath=$DEVICE_DIR/cache/$1
SavePath=$DEVICE_DIR/saves/$1
Width=$3
Height=$4
Bpp=32
AudioDriver=sdlaudio
CapFPS=30
Logging=1
# The intro videos play choppily on the MiSTer (and 0 plays them).
SkipIntroVideos=1
# Fog of war drawn with sprites (as in the original game) instead of blended triangles, which SDL draws slowly in software.
SpriteFogOfWar=1
CFG
}
write_cfg bg2 bg2 800 600
write_cfg bg1 bg1 640 480
write_cfg pst pst 640 480
write_cfg iwd how 640 480          # GemRB's game type for Icewind Dale with Heart of Winter and Trials of the Luremaster
write_cfg iwd2 iwd2 800 600        # Icewind Dale 2 has no 640x480 layout

cat > "$OUT/run.sh" <<'RUN'
#!/bin/sh
# Starts GemRB on the MiSTer for one game:   run.sh [bg2|bg1|pst|iwd|iwd2] [gemrb options...]      (default bg2)
# Optional settings go in /media/fat/gemrb/env.sh:
#   MISTER_RESOLUTION=640x480|800x600 skip the resolution question and use this
#   MISTER_OUTPUT_MODE=off           do not change the HDMI mode (otherwise it follows the chosen resolution)
#   MISTER_RESTORE_MODE="<modeline>" mode to switch back to afterwards (default 1080p60)
#   MISTER_DEBUG=1                   developer: run under gdb and write crash.log (needs deploy.sh debug)
#   MISTER_MALLOC_CHECK=1            developer: with MISTER_DEBUG, also check the heap on every allocation (slower)
#   MISTER_USB=/media/usbN           swap drive to use when several are plugged in (skips the question)
#   MISTER_SWAP=none                 developer: run without swap (the game can be killed when memory runs out)
#   MISTER_SWAP_MB=384               size of the emergency swap file (0 = none)
D=/media/fat/gemrb
cd "$D" || exit 1

GAME=bg2
if [ -n "$1" ] && [ -f "$D/GemRB-$1.cfg.default" ]; then GAME=$1; shift; fi

# The video driver switches this console to graphics mode while the game runs and back afterwards. If the game crashes it
# cannot, and the console then stays invisible (a black screen where the questions below should be). So put it back in text
# mode now, and again when the game ends however it ended.
reset_console() { python3 -c 'import fcntl; fcntl.ioctl(0, 0x4B3A, 0)' 2>/dev/null; }
reset_console

# Version 0.1.0 had a single game: game/, save/, cache/ and GemRB.cfg. Move them into the per-game layout.
if [ -d "$D/game" ] && [ ! -e "$D/games/bg2" ]; then
    mkdir -p "$D/games" "$D/saves" && mv "$D/game" "$D/games/bg2"
    [ -d "$D/save" ] && [ ! -e "$D/saves/bg2" ] && mv "$D/save" "$D/saves/bg2"
    rm -rf "$D/cache"
    if [ -f "$D/GemRB.cfg" ] && [ ! -f "$D/GemRB-bg2.cfg" ]; then
        sed -e "s|^GamePath=$D/game\$|GamePath=$D/games/bg2|" -e "s|^SavePath=$D/save\$|SavePath=$D/saves/bg2|" \
            -e "s|^CachePath=$D/cache\$|CachePath=$D/cache/bg2|" "$D/GemRB.cfg" > "$D/GemRB-bg2.cfg" && rm -f "$D/GemRB.cfg"
    fi
    rm -f "$D/GemRB.cfg.default"
fi

rm -f "$D/swapfile"                     # earlier versions kept the swap file on the SD card; it now lives on a USB drive

CFG="$D/GemRB-$GAME.cfg"
[ -f "$CFG" ] || cp "$D/GemRB-$GAME.cfg.default" "$CFG"
[ -f "$D/env.sh" ] && . "$D/env.sh"
mkdir -p "$D/cache/$GAME" "$D/saves/$GAME" "$D/games/$GAME"
if ! ls "$D/games/$GAME" 2>/dev/null | grep -qi '^chitin\.key$'; then
    echo "The game files for '$GAME' are not in $D/games/$GAME"
    echo "Copy the folder that contains CHITIN.KEY there (see INSTALL.txt)."
    sleep 10
    exit 1
fi
# Ask for the resolution every time (no default, so nobody is surprised by a screen mode their display dislikes). The answer is
# saved as Width/Height in the game's config, which also decides the HDMI mode below. Setting MISTER_RESOLUTION (for example in
# env.sh, or on the command line when testing) skips the question.
# Icewind Dale 2 was made for 800x600 and up and has no 640x480 layout; the other games offer both.
case "$GAME" in
    iwd2) RES_CHOICES="800x600" ;;
    *)    RES_CHOICES="640x480 800x600" ;;
esac
choose_resolution() {
    if [ -n "$MISTER_RESOLUTION" ]; then
        case " $RES_CHOICES " in
            *" $MISTER_RESOLUTION "*) RES=$MISTER_RESOLUTION; return 0 ;;
            *) echo "  $GAME does not support $MISTER_RESOLUTION (use one of: $RES_CHOICES)"; sleep 10; return 1 ;;
        esac
    fi
    set -- $RES_CHOICES
    if [ $# -eq 1 ]; then RES=$1; echo; echo "  $GAME uses $RES (the only size its interface supports)."; return 0; fi
    last=$(sed -n 's/^Width=\([0-9][0-9]*\).*/\1/p' "$CFG" | tail -1)x$(sed -n 's/^Height=\([0-9][0-9]*\).*/\1/p' "$CFG" | tail -1)
    while true; do
        echo
        echo "  Resolution for $GAME (last used: $last)"
        echo "    1) 640x480"
        echo "    2) 800x600"
        printf "  Type 1 or 2, then Enter: "
        read -r answer || return 1
        case "$answer" in
            1|640x480) RES=640x480; return 0 ;;
            2|800x600) RES=800x600; return 0 ;;
        esac
    done
}
choose_resolution || exit 1
case "$RES" in
    640x480) NEW_W=640; NEW_H=480 ;;
    800x600) NEW_W=800; NEW_H=600 ;;
    *) echo "Unsupported resolution '$RES' (use 640x480 or 800x600)"; sleep 10; exit 1 ;;
esac
sed -e "s/^Width=.*/Width=$NEW_W/" -e "s/^Height=.*/Height=$NEW_H/" "$CFG" > "$CFG.new" && mv "$CFG.new" "$CFG"

# Swap: the game needs more memory than the MiSTer has, so it needs a swap file, and that goes on a USB drive, never on the SD
# card (constant writes there would wear the card and are slow, since it is mounted synchronously). The drive must already have
# an ext4 filesystem mounted under /media/usbN with room to spare (FAT32 is far too slow: with the synchronous mount that USB
# drives get, creating the file runs at about 0.1 MB/s). Only one file, gemrb-swapfile, is added to it: nothing on the drive
# is erased, formatted or changed. MISTER_USB=/media/usbN picks the drive when several are plugged in.
SWAP_MB="${MISTER_SWAP_MB:-384}"
usb_mounts() {
    awk '$2 ~ /^\/media\/usb[0-9]+$/ && $3 == "ext4" { print $2 }' /proc/mounts
}
free_mb() { df -Pk "$1" 2>/dev/null | awk 'NR == 2 { print int($4 / 1024) }'; }
pick_usb() {
    need=$((SWAP_MB + 100)); usable=""
    for m in $(usb_mounts); do
        f=$(free_mb "$m")
        [ -n "$f" ] && [ "$f" -ge "$need" ] && usable="$usable $m"
    done
    set -- $usable
    if [ $# -eq 0 ]; then
        echo "  No USB drive with an ext4 filesystem and at least $need MB free was found."
        return 1
    fi
    if [ -n "$MISTER_USB" ]; then
        for m in "$@"; do [ "$m" = "$MISTER_USB" ] && { SWAP_DIR=$m; return 0; }; done
        echo "  $MISTER_USB is not a usable USB drive."; return 1
    fi
    if [ $# -eq 1 ]; then SWAP_DIR=$1; return 0; fi
    echo "  Which drive should hold the swap file? (only one file is added to it, nothing is erased)"
    i=1; for m in "$@"; do echo "    $i) $m ($(free_mb "$m") MB free)"; i=$((i + 1)); done
    printf "  Type a number, then Enter: "
    read -r pick || return 1
    i=1; for m in "$@"; do [ "$pick" = "$i" ] && { SWAP_DIR=$m; return 0; }; i=$((i + 1)); done
    return 1
}
choose_swap() {
    SWAPFILE=""; SWAP_DIR=""
    [ "$MISTER_SWAP" = none ] && return 0
    while true; do
        if pick_usb; then SWAPFILE="$SWAP_DIR/gemrb-swapfile"; return 0; fi
        echo
        echo "  $GAME needs a USB drive for swap memory (a ${SWAP_MB} MB file is added to it; nothing on the drive is erased)."
        echo "  Plug one in, then press Enter to look again, or type q and Enter to quit."
        printf "  > "
        read -r answer || return 1
        case "$answer" in q|Q) return 1 ;; esac
        sleep 2                         # give a freshly plugged drive a moment to mount
    done
}
choose_swap || exit 1

# Memory: the MiSTer has 490 MB of RAM and the game keeps everything it loads, so ask the C library not to waste any. One
# allocation pool instead of one per thread (each holds on to memory it has freed), and large blocks come straight from the
# system and go straight back (a fixed threshold, which also stops glibc raising it as the game runs). Set any of these in
# env.sh to override them.
export MALLOC_ARENA_MAX="${MALLOC_ARENA_MAX:-1}" MALLOC_MMAP_THRESHOLD_="${MALLOC_MMAP_THRESHOLD_:-131072}" MALLOC_TRIM_THRESHOLD_="${MALLOC_TRIM_THRESHOLD_:-131072}"
export GCONV_PATH="$D/libs/gconv" PYTHONHOME="$D/python" PYTHONDONTWRITEBYTECODE=1
export SDL_VIDEODRIVER="${SDL_VIDEODRIVER:-mister}" SDL_AUDIODRIVER="${SDL_AUDIODRIVER:-mister}"
export SDL_RENDER_DRIVER="${SDL_RENDER_DRIVER:-software}"
if [ "$SDL_RENDER_DRIVER" = software ]; then
    # SDL's software renderer asks for a window surface. Disable SDL's otherwise automatic hardware-renderer probe for
    # that surface so the software launcher cannot open a hidden Noodles session.
    export SDL_FRAMEBUFFER_ACCELERATION="${SDL_FRAMEBUFFER_ACCELERATION:-software}"
fi
# An alpha-less window surface lets SDL use its fast NEON blitter for the final composite.
export SDL_MISTER_FORMAT="${SDL_MISTER_FORMAT:-xrgb}"

# The MiSTer has about 490 MB of RAM and no swap, and the game (creature animations, and the old and new area while an area
# loads) can need more than that: the kernel then kills the game. So keep a swap file on the USB drive chosen above. The
# kernel is told to use it only as a last resort (swappiness 5). It is created in the background the first time (minutes on a
# slow drive) and kept for next time; it is switched off again when the game exits. It is attached to swap directly, which
# writes to the drive's blocks without going through the (synchronous) filesystem; if the filesystem does not allow that, it
# goes through a loop device instead.
swap_off() {
    for p in $(ps | grep -E "dd if=/dev/zero of=.*gemrb-swapfile" | grep -v grep | awk '{print $1}'); do kill "$p" 2>/dev/null; done
    for f in $(awk '/gemrb-swapfile/ { print $1 }' /proc/swaps); do swapoff "$f" 2>/dev/null; done
    for dev in $(losetup -a 2>/dev/null | grep "/gemrb-swapfile" | cut -d: -f1); do
        swapoff "$dev" 2>/dev/null
        losetup -d "$dev" 2>/dev/null
    done
    [ -n "$old_swappiness" ] && echo "$old_swappiness" > /proc/sys/vm/swappiness
}
swap_on() {
    [ -n "$SWAPFILE" ] && [ "$SWAP_MB" -gt 0 ] 2>/dev/null || return 0
    size=$((SWAP_MB * 1048576))
    if [ ! -f "$SWAPFILE" ] || [ "$(stat -c %s "$SWAPFILE")" != "$size" ]; then
        rm -f "$SWAPFILE"
        dd if=/dev/zero of="$SWAPFILE" bs=1M count="$SWAP_MB" 2>/dev/null || { rm -f "$SWAPFILE"; return 1; }
    fi
    chmod 600 "$SWAPFILE" 2>/dev/null
    if mkswap "$SWAPFILE" >/dev/null 2>&1 && swapon -p 0 "$SWAPFILE" 2>/dev/null; then
        :
    else
        dev=$(losetup -f) || return 1
        losetup "$dev" "$SWAPFILE" && mkswap "$dev" >/dev/null 2>&1 && swapon -p 0 "$dev" 2>/dev/null || { losetup -d "$dev" 2>/dev/null; return 1; }
    fi
    echo 5 > /proc/sys/vm/swappiness
}
old_swappiness=$(cat /proc/sys/vm/swappiness 2>/dev/null)
swap_off                                # clean up after a run that did not exit normally
swap_on &

# The scaler only scales the framebuffer by whole numbers, so switch the HDMI output itself to the
# game's resolution (the display scales it to fill the screen) and restore it afterwards.
W=$(sed -n 's/^Width=\([0-9][0-9]*\).*/\1/p' "$CFG" | tail -1)
H=$(sed -n 's/^Height=\([0-9][0-9]*\).*/\1/p' "$CFG" | tail -1)
case "${W}x${H}" in
    640x480)  MODELINE="640,16,96,48,480,10,2,33,25175,-hsync,-vsync" ;;      # VESA 640x480 @ 60 Hz
    800x600)  MODELINE="800,40,128,88,600,1,4,23,40000,+hsync,+vsync" ;;      # VESA 800x600 @ 60 Hz
    1024x768) MODELINE="1024,24,136,160,768,3,6,29,65000,-hsync,-vsync" ;;    # VESA 1024x768 @ 60 Hz
    *)        MODELINE="" ;;
esac
[ "$MISTER_OUTPUT_MODE" = off ] && MODELINE=""
MODE_1080P60="1920,88,44,148,1080,4,5,36,148500,+hsync,+vsync"     # CEA 1080p @ 60 Hz
switched=0
if [ -n "$MODELINE" ] && [ -p /dev/MiSTer_cmd ]; then
    echo "video_mode $MODELINE" > /dev/MiSTer_cmd
    switched=1
    sleep 2.5   # let the display re-sync; Main resizes the framebuffer to match
fi
# MISTER_DEBUG=1 (developer option) runs the game under gdb, with the unstripped files from `deploy.sh debug`, and writes the
# call stacks of every thread to crash.log if the game crashes. Adding MISTER_MALLOC_CHECK=1 also loads glibc's checking
# allocator (libc_malloc_debug), which stops the game at the first sign of heap corruption instead of much later (slower).
HEAP_PRELOAD=""; HEAP_CHECK=0; HEAP_PERTURB=0
if [ "$MISTER_MALLOC_CHECK" = 1 ] && [ -f "$D/libs/libc_malloc_debug.so.0" ]; then
    HEAP_PRELOAD="$D/libs/libc_malloc_debug.so.0"; HEAP_CHECK=3; HEAP_PERTURB=165
fi
if [ "$MISTER_DEBUG" = 1 ] && command -v gdb >/dev/null 2>&1; then
    # gdb has its own Python: keep GemRB's PYTHONHOME and GCONV_PATH away from it, and give them to the game inside it.
    env -u PYTHONHOME -u GCONV_PATH gdb -batch -ex "set pagination off" -ex "set startup-with-shell off" -ex "set debug-file-directory $D/debug" \
        -ex "set environment PYTHONHOME $D/python" -ex "set environment GCONV_PATH $D/libs/gconv" \
        -ex "set environment LD_PRELOAD $HEAP_PRELOAD" -ex "set environment MALLOC_CHECK_ $HEAP_CHECK" -ex "set environment MALLOC_PERTURB_ $HEAP_PERTURB" \
        -ex "handle SIGPIPE nostop noprint pass" -ex "handle SIGUSR1 nostop noprint pass" -ex "handle SIGUSR2 nostop noprint pass" \
        -ex run -ex "echo \n=== the game stopped ===\n" -ex "info program" -ex "bt 40" -ex "thread apply all bt 15" \
        -ex "echo \n=== main thread stack (glibc frames cannot be unwound after abort) ===\n" -ex "thread 1" -ex "x/700a \$sp" \
        --args "$D/gemrb" -c "$CFG" "$@" > "$D/crash.log" 2>&1 &
else
    "$D/gemrb" -c "$CFG" "$@" &
fi
child=$!
trap 'kill -TERM $child 2>/dev/null' TERM HUP INT
wait $child
rc=$?
wait $child 2>/dev/null
reset_console
# Always leave a short record of how the game ended (a crash is 128 plus the signal: 139 = segfault, 134 = abort, 137 = killed).
{
    echo "$(date '+%F %T') $GAME exit=$rc $(grep -E 'MemAvailable|SwapFree' /proc/meminfo | tr -s ' ' | tr '\n' ' ')"
    dmesg 2>/dev/null | grep -i -E 'out of memory|oom-kill' | tail -1
} >> "$D/last-run.log"
tail -50 "$D/last-run.log" > "$D/last-run.log.new" && mv "$D/last-run.log.new" "$D/last-run.log"
swap_off
if [ "$switched" = 1 ]; then
    echo "video_mode ${MISTER_RESTORE_MODE:-$MODE_1080P60}" > /dev/MiSTer_cmd
    sleep 1
fi
exit $rc
RUN
chmod +x "$OUT/run.sh"

# Parallel hardware-renderer entry point. The standard run.sh keeps its
# software default so this path can be selected and qualified independently.
cat > "$OUT/run-noodles.sh" <<'RUN_NOODLES'
#!/bin/sh
set -e
D=/media/fat/gemrb
[ -f "$D/env.sh" ] && . "$D/env.sh"
RBF="${MISTER_NOODLES_RBF:-/media/fat/pet/Noodles_descriptor_ring_seed13.rbf}"
LAUNCH_TTY="$(tty 2>/dev/null || true)"
if [ "$LAUNCH_TTY" != /dev/tty2 ] && [ "${MISTER_NOODLES_ALLOW_DIRECT:-0}" != 1 ]; then
    echo "Launch Noodles games from MiSTer's OSD Scripts menu so Main releases the mouse and keyboard."
    echo "Direct shell launch is refused because Main keeps exclusive evdev grabs outside the Scripts path."
    exit 1
fi
case "$RBF" in
    /*) ;;
    *) echo "MISTER_NOODLES_RBF must be an absolute path: $RBF"; exit 1 ;;
esac
if [ ! -r "$RBF" ]; then
    echo "MiSTer-Noodles RBF not found: $RBF"
    echo "Copy the protocol 1.5 seed-13 RBF there or set MISTER_NOODLES_RBF in $D/env.sh."
    exit 1
fi
if [ ! -p /dev/MiSTer_cmd ]; then
    echo "/dev/MiSTer_cmd is unavailable; cannot load MiSTer-Noodles or release Main input."
    exit 1
fi

# Main's OSD Scripts path relinquishes its evdev grabs before this wrapper
# starts. Reloading Noodles here gives the game a clean hardware session while
# preserving that handoff. The core owns its fixed 800x600 output, so do not
# ask Main to switch the separate Linux framebuffer/output mode around it.
printf 'load_core %s\n' "$RBF" > /dev/MiSTer_cmd
sleep 3
export SDL_RENDER_DRIVER=noodles
export MISTER_RESOLUTION=800x600
export MISTER_OUTPUT_MODE=off
exec "$D/run.sh" "$@"
RUN_NOODLES
chmod +x "$OUT/run-noodles.sh"

# One entry per game for the OSD Scripts menu (F12 > Scripts).
for g in bg2 bg1 pst iwd iwd2; do
	printf '#!/bin/bash\nexec %s/run.sh %s "$@"\n' "$DEVICE_DIR" "$g" > "$WORK/bundle/Scripts/gemrb-$g.sh"
	printf '#!/bin/bash\nexec %s/run-noodles.sh %s "$@"\n' "$DEVICE_DIR" "$g" > "$WORK/bundle/Scripts/gemrb-noodles-$g.sh"
	chmod +x "$WORK/bundle/Scripts/gemrb-$g.sh"
	chmod +x "$WORK/bundle/Scripts/gemrb-noodles-$g.sh"
done
du -sh "$WORK/bundle"; du -sh "$OUT"/*
